//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.12 at 11:30:37 AM CET 
//


package models.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatiRapportoCCIType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiRapportoCCIType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceInput" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nkSportello" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nkConto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiRapportoCCIType", propOrder = {
    "serviceInput",
    "nkSportello",
    "nkConto"
})
public class DatiRapportoCCIType {

    //@XmlElement(required = true)
    protected String serviceInput;
   //@XmlElement(required = true)
    protected String nkSportello;
    //@XmlElement(required = true)
    protected String nkConto;

    /**
     * Gets the value of the serviceInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceInput() {
        return serviceInput;
    }

    /**
     * Sets the value of the serviceInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceInput(String value) {
        this.serviceInput = value;
    }

    /**
     * Gets the value of the nkSportello property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNkSportello() {
        return nkSportello;
    }

    /**
     * Sets the value of the nkSportello property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNkSportello(String value) {
        this.nkSportello = value;
    }

    /**
     * Gets the value of the nkConto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNkConto() {
        return nkConto;
    }

    /**
     * Sets the value of the nkConto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNkConto(String value) {
        this.nkConto = value;
    }

}
