//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.12 at 11:30:37 AM CET 
//


package models.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JdfInputDataFornkDatiRapportoCC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JdfInputDataFornkDatiRapportoCC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bnpp.com/jdf/service/nk/datirapportocc/input}DatiRapportoCCIType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JdfInputDataFornkDatiRapportoCC", propOrder = {
    "datiRapportoCCIType"
})
public class JdfInputDataFornkDatiRapportoCC {

    @XmlElement(name = "DatiRapportoCCIType", required = true)
    protected DatiRapportoCCIType datiRapportoCCIType;

    /**
     * Gets the value of the datiRapportoCCIType property.
     * 
     * @return
     *     possible object is
     *     {@link DatiRapportoCCIType }
     *     
     */
    public DatiRapportoCCIType getDatiRapportoCCIType() {
        return datiRapportoCCIType;
    }

    /**
     * Sets the value of the datiRapportoCCIType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiRapportoCCIType }
     *     
     */
    public void setDatiRapportoCCIType(DatiRapportoCCIType value) {
        this.datiRapportoCCIType = value;
    }

}
